version: "3.9"
services:
  api:
    build:
      context: ./api
      network: host
    ports:
      - "20243:8000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build:
      context: ./mysql
      network: host
    volumes:
      - mysql_v:/var/lib/mysql
    env_file:
      - ./mysql/mysql.env
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 2s
      interval: 2s
      retries: 10

volumes:
  mysql_v: