apiVersion: v1
kind: Service
metadata:
  labels:
    service: api
  name: api
spec:
  ports:
    - name: api-port
      port: 20243
      targetPort: 8000
      nodePort: 30000
  type: NodePort
  selector:
    service: api
